apiVersion: v2
name: justera
description: A Helm chart for signing documnets
type: application
version: 0.1.0
appVersion: 0.1.0

dependencies:
  - name: elasticsearch
    version: 12.0.1
    repository: https://charts.bitnami.com/bitnami
    tags:
      - documentStore
  - name: kibana
    version: 5.0.17
    repository: https://charts.bitnami.com/bitnami
    tags:
      - documentStore
  - name: logstash
    version: 0.2.18
    repository: https://charts.bitnami.com/bitnami
    tags:
      - documentStore

