apiVersion: v2
name: justera
description: A Helm chart for signing documnets
type: application
version: 0.1.0
appVersion: 0.1.0

dependencies:
  - name: elasticsearch
    version: ~11.0.16
    repository: https://charts.bitnami.com/bitnami
    tags:
      - documentStore
