# Custom values

# Defaults
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

nodeSelector: {}
tolerations: []
affinity: {}

############################     elasticsearch     ############################
elasticsearch:
  plugins:
    - ingest-attachment

################################     kibana     ################################
kibana:
  elasticsearch:
    hosts:
    - elasticsearch-elasticsearch-coordinating-only
    port: 9200


